language: node_js
node_js:
  - 8.9.0
deploy:
  provider: firebase
  token:
    secure: tHndG241Bae2exQ5Swlr0wM1LGXmQp3cGGzAEy/qTWkW9rBLz0F+fe6vhK6YzOhjrK9U/nicLvIHcjp6geYQUkxLbUk425QWRl07pxLABWdxzy7Q8ZufSKhYtvsSEwlmjV84rT1Nprew/IUfF6pRKLI5uRuaH1meKyl/8O4ZCJV1cuJMtvONI3ymtSTbaBeRNLx4+9svM3Zl01Xhjd5/vqmz78wKI0ZhdDs/UJCrtH9APZFze9AXLKf4jlKADU2uhGtJ+PeC0F4UOoUDjvOU6SxmnVEpnG1T21g03h7fVWdfCTJjiq1G8KfruoeKw4kGtGirZCT4+8UHH+/mtrloD4tBp+BeqK9KDX0OdKACSiPTxyzRVnzRX+8M6Ez2I2P3cEX55ivpZz7rFB4V+hnNtcCpbTOgfp106Vf6nrMh79colrQzeLcHEnGzQLPpzKjXN8x7Rqvu90trLkYlEYHiC2qs+8ymykgybbi9jT4c4+OZr1EHVVxGGKTwcMwk3dz53SqAMYUCInhLnFtUw74JT2TKqaE8E3f/T2sv7EdeBYy4vyMJsyPD89iqBEfWtirzEAO0ClOcAL1IsJMWkBODHbaW6vGnI6fM8guW8PwMurrQUBGM7EeDQOa9rcB//YWSOPPeqG5PhljepjK9KMEnXhOusxF/xhunlrTPwcHtj2Y=
  project: "embracebook-e403d"
  skip_cleanup: true
before_install:
  - npm i
before_deploy:
  - npm run build
cache:
  directories:
    - "node_modules"
